local ReplicatedStorage = game:GetService "ReplicatedStorage"
local lifetimes = require(ReplicatedStorage.code.systems.lifetimes)
local replecs_client = require(script.Parent.systems.replecs_client)
local transforms = require(ReplicatedStorage.code.systems.transforms)
local apply_colors = require(script.Parent.systems.apply_colors)
local player_movement = require(script.Parent.systems.player_movement)

local ordered: { string | ((...any) -> ()) } = {
	"__other__",
	replecs_client,
	player_movement,
	transforms,
	apply_colors,
	lifetimes,
}

return ordered
