local jecs = require "./jecs"
local common = require "@self/common"
local types = require "@self/types"
local utils = require "@self/utils"

local client = require "@self/client"
local server = require "@self/server"
local customid = require "@self/customid"
local interpolation = require "@self/interpolation"
local VERSION = require "@self/ver"

export type Server = server.Server
export type Client = client.Client

type Entity = common.Entity
type World = common.World
type Component<T = any> = common.Component<T>

export type HandleContext = customid.HandleContext
export type CustomId = customid.CustomId
export type HandshakeInfo = types.HandshakeInfo
export type Serdes = types.Serdes
export type OwnershipValidator = types.OwnershipValidator
export type InterpolatorConfig = interpolation.InterpolatorConfig
export type Interpolator = interpolation.Interpolator

export type ReplecsLib = {
	server: Server,
	client: Client,
	components: types.Components,

	after_replication: (self: ReplecsLib, callback: () -> ()) -> (),
	register_custom_id: (self: ReplecsLib, custom_id: CustomId) -> (),

	set_serdes: <T>(self: ReplecsLib, id: Component<T>, serdes: types.Serdes<T>) -> (),
	remove_serdes: (self: ReplecsLib, id: Component) -> (),
	set_validator: <T>(self: ReplecsLib, id: Component<T>, validator: types.OwnershipValidator<T>) -> (),
	remove_validator: (self: ReplecsLib, id: Component) -> (),
}

type Replecs = types.Components & {
	__index: any,
	VERSION: string,
	create: (world: World?) -> ReplecsLib,

	create_server: (world: World?) -> Server,
	create_client: (world: World?) -> Client,
	create_custom_id: (identifier: string, handler: (ctx: HandleContext) -> Entity?) -> CustomId,
	create_interpolation: (config: interpolation.InterpolatorConfig?) -> interpolation.Interpolator,
}

local replecs = {}
replecs.VERSION = VERSION
replecs.__index = replecs

local PREREGISTRATION = common.preregistration

if PREREGISTRATION then
	local components = replecs :: Replecs
	utils.create_components(common.preregister_tag, common.preregister_component, components)
	utils.add_component_names(components, common.add_preregistered_name)

	jecs.meta(components.custom, jecs.Exclusive)
	jecs.meta(components.global, jecs.Exclusive)
end

local COMPONENTS = if PREREGISTRATION then replecs :: Replecs else nil

function replecs.create_server(world: World?): Server
	return server.create(world, COMPONENTS)
end

function replecs.create_client(world: World?): Client
	return client.create(world, COMPONENTS)
end

function replecs.create(world: World?): ReplecsLib
	assert(game, "This is a Roblox specific function")
	local RunService = game:GetService "RunService"
	local self = {} :: ReplecsLib

	if COMPONENTS then
		self.components = COMPONENTS
	elseif world then
		self.components = utils.create_components(utils.tag_factory(world), utils.component_factory(world))
		utils.add_component_names(self.components, function(component, name)
			common.add_name(world, component, name)
		end)
	end

	if RunService:IsServer() then
		self.server = server.create(world, self.components)
	end
	if RunService:IsClient() then
		self.client = client.create(world, self.components)
	end

	return setmetatable(self, replecs) :: any
end

function replecs.create_custom_id(identifier: string, handler: (ctx: HandleContext) -> Entity?)
	return customid.create(identifier, handler)
end

function replecs.create_interpolation(config: interpolation.InterpolatorConfig?)
	return interpolation.create(config)
end

function replecs.after_replication(lib: ReplecsLib, callback: () -> ())
	local lib_client = lib.client
	if lib_client then
		lib_client:after_replication(callback)
	else
		callback()
	end
end

function replecs.register_custom_id(lib: ReplecsLib, custom_id: CustomId)
	if lib.server then
		lib.server:register_custom_id(custom_id)
	end
	if lib.client then
		lib.client:register_custom_id(custom_id)
	end
end

function replecs.set_serdes(lib: ReplecsLib, id: Component, serdes: Serdes)
	if lib.server then
		lib.server:set_serdes(id, serdes)
	end
	if lib.client then
		lib.client:set_serdes(id, serdes)
	end
end

function replecs.remove_serdes(lib: ReplecsLib, id: Component)
	if lib.server then
		lib.server:remove_serdes(id)
	end
	if lib.client then
		lib.client:remove_serdes(id)
	end
end

function replecs.set_validator(lib: ReplecsLib, id: Component, validator: types.OwnershipValidator)
	if lib.server then
		lib.server:set_validator(id, validator)
	end
end

function replecs.remove_validator(lib: ReplecsLib, id: Component)
	if lib.server then
		lib.server:remove_validator(id)
	end
end

return replecs :: Replecs
